name: Publish

on:
  push:
    branches:
      - master
    tags:
      - v.*

jobs:
  sbt:
    name: sbt publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9
      - name: Publish
        run: |-
          cp .jvmopts-travis .jvmopts
          sbt ++2.12.11 ci-release
          sbt ++2.13.3 akka-grpc-runtime/ci-release ++2.13.3! akka-grpc-codegen/ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  gradle:
    name: Gradle
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9
      - name: Publish
        run: |-
          openssl aes-256-cbc -K $encrypted_9c9c33071881_key -iv $encrypted_9c9c33071881_iv -in gradle.properties.enc -out ./gradle-plugin/gradle.properties -d
          cd gradle-plugin
          ./gradlew publishPlugins

  documentation:
    name: Documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11.0-9
      - name: Publish
        run: |-
          eval "$(ssh-agent -s)"
          echo $SCP_SECRET | base64 -d > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          ssh-add /tmp/id_rsa
          cp .jvmopts-travis .jvmopts
          sbt akka-grpc-docs/publishRsync
        env: SCP_SECRET: ${{ secrets.SCP_SECRET }}
